name: E2E Tests
on: push

jobs:
  e2e:
    runs-on: ubuntu-latest
    name: E2E on Chrome

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Cypress e2e tests
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          record: false
          build: npm run build
          start: npm run dev
          spec: cypress/e2e/app/index.cy.ts